"""user image

Revision ID: ae1bc2b73330
Revises: 2914a9c61e89
Create Date: 2020-07-12 13:21:14.737640

"""
from alembic import op
import sqlalchemy as sa
import flask_image_alchemy


# revision identifiers, used by Alembic.
revision = 'ae1bc2b73330'
down_revision = '2914a9c61e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', flask_image_alchemy.fields.StdImageField(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['user_image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    # ### end Alembic commands ###
